name : pytest_action

on:
  push:
  pull_request:

jobs:
  run-tests:
    strategy:
      fail-fast : false
      matrix:

        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"

    name: test
    runs-on : ubuntu-latest

    steps:
      - name: Checkout Code
        uses : actions/checkout@v3
      
      - name : Setup Python
        uses : actions/setup-python@v4
        with:
          name: ${{ matrix.python-version }}

      - name : Install PostgreSQL
        run : sudo apt update ; sudo apt install postgresql postgresql-contrib ; sudo systemctl start postgresql ; sudo -u postgres createuser --no-password moon ; sudo systemctl restart postgresql

      - name : Install Dependencies
        run : python -m pip install pytest ; pip install -r requirements.txt

      - name : Run Tests
        run : python -m pytest tests/test_moon.py
